feat: add option to refresh on visibilitychange event
mittwald/react-use-promise pull request #277
Opened 2024-11-19 12:42 UTC by maaaathis

2024-11-19 12:48 UTC, mfal requested changes

2024-11-19 12:48 UTC, mfal commented on src/lib/useOnVisibilityChange.ts
> +type Callback = () => void;
```suggestion
type Callback = (isVisible: boolean) => void;
```

2024-11-19 12:48 UTC, mfal commented on src/resource/useWatchResourceValue.ts
> +    refreshOnVisibilityChange = false,
Könnte mir vorstellen, dass das im Default von `refreshOnWindowFocus` abhängt. 

```suggestion
    refreshOnVisibilityChange = refreshOnWindowFocus,
```

2024-11-19 12:48 UTC, mfal commented on src/resource/useWatchResourceValue.ts
> +  }, [resource, refreshOnVisibilityChange]);
```suggestion
  useOnVisibilityChange((isVisible) => {
    if (refreshOnVisibilityChange && isVisible) {
      resource.refresh();
    }
  }, [resource, refreshOnVisibilityChange]);
```

2024-11-19 12:50 UTC, maaaathis commented on src/resource/useWatchResourceValue.ts
> +    refreshOnVisibilityChange = false,
Jau, das kann man hier gut machen 👍

2024-11-20 07:24 UTC, mfal requested changes

2024-11-20 07:24 UTC, mfal commented on src/resource/types.ts
> +  refreshOnVisibilityChange?: boolean;
Wäre eher bei diesem Wording. Man könnte sonst denken es geht um die Visibility des React-Elementes, indem der Hook getriggered wurde.

```suggestion
  refreshOnDocumentVisibilityChange?: boolean;
```

2024-11-20 08:09 UTC, mfal approved these changes

2024-11-20 08:09 UTC, merged